### ISSUE TITLE
Using PublishComposite, changing Parent document causes Isotope to not display last child item created.

### ISSUE THREAD

**Issue by nadeemja** [jorisroling/meteor-isotope#1]
Hi,

I'm using PublishComposite together with meteor-isotope.

Everything works, except this:
1. Set up a ReactiveJoin using PublishComposite, for example Article and Comments.
2. Use Isotope to display Comments
3. Make any change to the Article document.
4. Try to add a comment.
5. Comment doesn't display, unless page is refreshed or another comment is added.

Please help :)

**Comment by nadeemja** [comment]
Can confirm that this also happens when not using PublishComposite.

**Comment by jorisroling** [comment]
Can you share your code?

Regards,
Joris

**Comment by nadeemja** [comment]
Yes, but what specifically would you need?

**Comment by jorisroling** [comment]
A project, showing the problems you have...

**Comment by nadeemja** [comment]
I understand. It's a closed source company code. What would be the best way to share it with you?

**Comment by jorisroling** [comment]
Could you make a mini project, showing your problem. And share that with me. Possible?

**Comment by nadeemja** [comment]
Might be. I will look into it. 

For a start, would it suffice if I gave you access and instructions to try out a deployed version of the app? 

Thank you for helping me out on this :)

**Comment by jorisroling** [comment]
Let's try...

J*

**Comment by nadeemja** [comment]
Great. 

Here are some instructions to reproduce the issue.
1. Go to test.sembly.no
2. Login in with **testaccount@stud.ntnu.no** and **password**.
3. If not automatically redirected, go to: https://test.sembly.no/schedules/92ruYo4gLSBefNMEP
4. Click the blue button on the bottom called "Spør Underviser" (Ask teacher), fill in some text and hit ok.
5. Observe that a new item has been added. Feel free to add more. This is the expected behavior.
6. Now, click the red button called "Jeg falt av!" (I fell off). It should start to spin.
7. Then, using the blue button add another question. For clarity, you might use the text "This will not show, until I add another question or reload the page."
8. Observe that nothing happens.
9. Add another question using the blue button, feel free to call it "This wont show, but the previous one will."
10. Feel free to turn the red button on and off - it wont matter. 

I have confirmed that is not an UI issue, by removing all code related to the red button functionality, and changing the Schedules document manually and directly using 3T MongoChef. 

I've also tried disabling PublishComposite, and separating out the subscriptions. Doesn't matter. 

I'm going to attach all the client side code, since that is available to you anyways. Hopefully this will be enough. Otherwise, I will try to create that mini-project you requested. 
[Archive.zip](https://github.com/jorisroling/meteor-isotope/files/182162/Archive.zip)

**Comment by jorisroling** [comment]
Please try the following:
For every card, add an image (<img src="...">). Use the same image, doesn't matter. See if it helps. If it does, we''l fix it. ok?

J*

**Comment by nadeemja** [comment]
Thank you so much for checking it out, and offering a solution. Will try it immediately. Do you mean something like this: 

```
  <template name="studentQuestionItem">
    <div class='studentQuestionItem'>
     <img src="somethingsomething.jpg">
      <div class="panel panel-white post panel-shadow">
        <div class="post-heading">
          <div class="pull-right ">

            <i class="fa fa-clock-o"></i>
            {{prettyCreatedAt}}
          </div>
          <div class="pull-left meta">
            <i class="fa fa-user"></i>
            <b>{{author}}</b>

          </div>
        </div>
        <div class="post-description">
          <p>
            {{> editableText collection='questions' field='body' textarea='true' userCanEdit=userIsOwner inputClass="form-control"}}

          </p>
          <div class="stats">
            <a href="#" class="btn btn-default stat-item">
              <i class="fa fa-thumbs-up icon"></i>2
            </a>
            <a href="#{{_id}}" class="btn btn-default stat-item showDiscussionComments">
              <i class="fa fa-reply"></i>
              {{ discussionCommentsCount }}
            </a>
          </div>
        </div>
      </div>
    </div>
  </template>
```

**Comment by jorisroling** [comment]
yes, please try that.

J*

**Comment by nadeemja** [comment]
I did. It did not help. Here's the code I tried. 

```
  <template name="studentQuestionItem">
    <div class='studentQuestionItem'>

      <div class="panel panel-white post panel-shadow">
        <img src="/Sembly-logo.png" alt="" width='10px'>

        <div class="post-heading">
          <div class="pull-right ">

            <i class="fa fa-clock-o"></i>
            {{prettyCreatedAt}}
          </div>
          <div class="pull-left meta">
            <i class="fa fa-user"></i>
            <b>{{author}}</b>

          </div>
        </div>
        <div class="post-description">
          <p>
            {{> editableText collection='questions' field='body' textarea='true' userCanEdit=userIsOwner inputClass="form-control"}}

          </p>
          <div class="stats">
            <a href="#" class="btn btn-default stat-item">
              <i class="fa fa-thumbs-up icon"></i>2
            </a>
            <a href="#{{_id}}" class="btn btn-default stat-item showDiscussionComments">
              <i class="fa fa-reply"></i>
              {{ discussionCommentsCount }}
            </a>
          </div>
        </div>
      </div>
    </div>
  </template>
```

**Comment by nadeemja** [comment]
Out of curiosity, what do you think could be causing this? 
It seems like you have a theory.

**Comment by jorisroling** [comment]
In the isotope loader, I use a kind of if (imagesLoaded) do layout

See the repo, isotope.js line 156.

J*

**Comment by jorisroling** [comment]
I also see this, 
after a hard reload (⌘R if you are on apple), the problem is not there.

J*

**Comment by jorisroling** [comment]
The problem, happens when you either switch on the red spinner, or (after hard reload), switch it off.
What happens when one taps the red spinner?

J*

**Comment by nadeemja** [comment]
I see. 

Well, here is the event-handler for click the red button.

```
'click #iFellOffButton': function ( e ) {

  e.preventDefault();
  $( 'i.fa-exclamation-triangle' ).toggleClass( 'fa-spin' );


  Meteor.call( "schedulesUpdateFallenOfUserIds", FlowRouter.current().params.scheduleId, function ( error, result ) {
    if ( error ) {
      console.log( "error", error );
    }
    if ( result ) {
      console.log( result );

    }
  } );


},
```

Here is the code for 'schedulesUpdateFallenOfUserIds' method:

```
schedulesUpdateFallenOfUserIds: function ( scheduleId ) {
    check( scheduleId, String );
    schedule = Schedules.findOne( {
        _id: scheduleId
    } );

    if ( !schedule ) {
        return null;
    }

    if ( !_.contains( schedule.user_ids, Meteor.userId() ) ) {
        return null;
    }

    if ( _.contains( schedule.fallenOffUserIds, Meteor.userId() ) ) {
        Schedules.update( {
            _id: scheduleId
        }, {
            $pull: {
                fallenOffUserIds: Meteor.userId()
            }
        } );
        return 'User is not longer fallen off.';
    }
    else {
        Schedules.update( {
            _id: scheduleId
        }, {
            $addToSet: {
                fallenOffUserIds: Meteor.userId()
            }
        } );

        return 'User ser to fallen off';
    }

},
```

Here is the Schedule document before clicking (deactivated): 

```
{
    "_id": "92ruYo4gLSBefNMEP",
    "ext_id": 45995,
    "title": "TMT4110",
    "event_id": "LKRaeqmg4h6xZntzQ",
    "start_time": "2016-03-18T10:15:00.000+01:00",
    "end_time": "2016-03-18T12:00:00.000+01:00",
    "user_ids": [
      "4eyQoNhcxbtMbWJWx",
      "nvpEMuBYRKFwg7TjH",
      "Ng99uZrNqxNv4XGqp",
      "J6DEaqojM8wnzoT3v",
      "3EanEXTtXe8L9WP42",
      "5nTLKrTz5fba9DYdS",
      "froEg97LqpBEh4b64",
      "WzLbZaTvLoBHJmqST",
      "5WSWa7yTMu5cDL95G",
      "7Qy9Qvupjwh5shGeT",
      "E53gvxZxec9x6iCHw",
      "FhzmgsfaxyGSeWvTc"
    ],
    "lecturers": [
      {
        "_id": "4eyQoNhcxbtMbWJWx",
        "profile": {
          "name": "Frode Seland"
        },
        "emails": [
          {
            "address": "frode.seland@ntnu.no",
            "verified": false
          },
          {
            "address": "frodesel@ntnu.no",
            "verified": false
          }
        ]
      }
    ],
    "fallenOffUserIds": []
  }
```

And here it is after clicking the red button: 

```
  {
    "_id": "92ruYo4gLSBefNMEP",
    "ext_id": 45995,
    "title": "TMT4110",
    "event_id": "LKRaeqmg4h6xZntzQ",
    "start_time": "2016-03-18T10:15:00.000+01:00",
    "end_time": "2016-03-18T12:00:00.000+01:00",
    "user_ids": [
      "4eyQoNhcxbtMbWJWx",
      "nvpEMuBYRKFwg7TjH",
      "Ng99uZrNqxNv4XGqp",
      "J6DEaqojM8wnzoT3v",
      "3EanEXTtXe8L9WP42",
      "5nTLKrTz5fba9DYdS",
      "froEg97LqpBEh4b64",
      "WzLbZaTvLoBHJmqST",
      "5WSWa7yTMu5cDL95G",
      "7Qy9Qvupjwh5shGeT",
      "E53gvxZxec9x6iCHw",
      "FhzmgsfaxyGSeWvTc"
    ],
    "lecturers": [
      {
        "_id": "4eyQoNhcxbtMbWJWx",
        "profile": {
          "name": "Frode Seland"
        },
        "emails": [
          {
            "address": "frode.seland@ntnu.no",
            "verified": false
          },
          {
            "address": "frodesel@ntnu.no",
            "verified": false
          }
        ]
      }
    ],
    "fallenOffUserIds": [
      "FhzmgsfaxyGSeWvTc"
    ]
  }
```

As I've said earlier, remove everything related to this red button and manually updating the fallenOffUserIds the Schedules document directly through mongodb queries, still causes the issue.

**Comment by nadeemja** [comment]
Are you able to produce this error on any of your own existing apps using analogous code logic?

**Comment by jorisroling** [comment]
Actually: no.

**Comment by nadeemja** [comment]
Ok.

Here is another way to reproduce the issue:
1. Go to https://test.sembly.no/schedules/92ruYo4gLSBefNMEP
2. Open console
3. Run Schedules.update({_id: '92ruYo4gLSBefNMEP'}, {$set: {title: 'hei'}})
4. The command will be denied, but it will still cause the same bug.

What are we to make of this?

**Comment by nadeemja** [comment]
This is getting stranger and stranger... 

I moved the fallenOffUserIds to another collection (`Statistics´) and the same bug.

**Comment by nadeemja** [comment]
It seems that even attempting to update any of the documents from any collection causes this bug. How can this be?

**Comment by jorisroling** [comment]
I'm as confused as you...

J*

**Comment by nadeemja** [comment]
It also happens with smeevil/reactive-block-grid.

**Comment by nadeemja** [comment]
Would it be possible to run a certain code on a set interval as a temporary fix?

**Comment by nadeemja** [comment]
Sorry to be a bother, but running this manually in the console seems to be a workaround: 

```
elem = $('li[data-isotope-position]').first(); 
$('ul.isotope').isotope('insert', elem).isotope('layout');
```

Not sure if it gives you any hints...

**Comment by nadeemja** [comment]
I figured out what this was. Will create new issue.
